const ActionTypes = {
    DO_FORM_VALIDATION: 'DO_FORM_VALIDATION',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    IMAGE_UPLOAD_ERROR: 'IMAGE_UPLOAD_ERROR',
    MEMBER_ADD_ATTEMPT: 'MEMBER_ADD_ATTEMPT',
    MEMBER_ADD_SUCCESS: 'MEMBER_ADD_SUCCESS',
    MEMBER_ADD_ERROR: 'MEMBER_ADD_ERROR',

    GET_MEMBER_PENDING: 'GET_MEMBER_PENDING',
    GET_MEMBER_SUCCESS: 'GET_MEMBER_SUCCESS',
    GET_MEMBER_ERROR: 'GET_MEMBER_ERROR',

    READ_MEMBER_PENDING: 'READ_MEMBER_PENDING',
    READ_MEMBER_SUCCESS: 'READ_MEMBER_SUCCESS',
    READ_MEMBER_ERROR: 'READ_MEMBER_ERROR',

    UPDATE_MEMBER_PENDING: 'UPDATE_MEMBER_PENDING',
    UPDATE_MEMBER_SUCCESS: 'UPDATE_MEMBER_SUCCESS',
    UPDATE_MEMBER_ERROR: 'UPDATE_MEMBER_ERROR',

    DELETE_MEMBER_PENDING: 'DELETE_MEMBER_PENDING',
    DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
    DELETE_MEMBER_ERROR: 'DELETE_MEMBER_ERROR'
};

export default ActionTypes;