const ActionTypes = {
    DO_FORM_VALIDATION: 'DO_FORM_VALIDATION',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    IMAGE_UPLOAD_ERROR: 'IMAGE_UPLOAD_ERROR',
    MEMBER_ADD_ATTEMPT: 'MEMBER_ADD_ATTEMPT',
    MEMBER_ADD_SUCCESS: 'MEMBER_ADD_SUCCESS',
    MEMBER_ADD_ERROR: 'MEMBER_ADD_ERROR'
};

export default ActionTypes;