const ActionTypes = {
    ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
    LOGGED_IN: 'LOGGED_IN',
    LOGGED_IN_ERROR: 'LOGGED_IN_ERROR',
    VERIFY_AUTH_USER: 'VERIFY_AUTH_USER'
};

export default ActionTypes;